USE kodilla_tester;

DROP TABLE IF EXISTS ISSUES;
DROP TABLE IF EXISTS ISSUESLISTS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID          SERIAL PRIMARY KEY,
    FIRSTNAME   VARCHAR(100),
    LASTNAME    VARCHAR(100)
);

CREATE TABLE ISSUESLISTS
(
ID		SERIAL PRIMARY KEY,
NAME	ENUM ("TO DO", "IN PROGRESS", "DONE") NOT NULL
);

CREATE TABLE ISSUES
(
ID 					SERIAL PRIMARY KEY,
ISSUESLIST_ID		BIGINT UNSIGNED NOT NULL,
SUMMARY 			VARCHAR(150) CHARSET utf8 NOT NULL,
DESCRIPTION 		VARCHAR(1000) CHARSET utf8,
USER_ID_ASSIGNEDTO	BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS (ID),
FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS (ID)
);

INSERT INTO ISSUESLISTS (NAME)
VALUES ("TO DO");

INSERT INTO ISSUESLISTS (NAME)  
VALUES ("IN PROGRESS");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("DONE");

COMMIT;

INSERT INTO USERS(FIRSTNAME, LASTNAME) VALUES  ("JOHN", "KOWALSKI");/*TODO Pls add more users */

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "LOGIN FAILURE", "PASSWORD RESET NEEDED", "1"); /*TODO  Pls correct -> USER_ID_ASSIGNEDTO is not String*/

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "LOGIN FAILURE", "PASSWORD CHANGED AND USER CONTACTED", "4");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "PRINTER ISSUE", "USER CONTACTED IN ORDER TO CONNECT THE PRINTER TO THE NETWORK PROPERLY", "1");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "PRINTER ISSUE", "ISSUE SOLVED, USER IS ABLE TO PRINT", "1");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "PRINTER ISSUE", "USER IS NOT ABLE TO PRINT, PRINTER TO BE CONNECTED TO THE NETWORK", "2");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "PRINTER ISSUE", "USER IS NOT ABLE TO PRINT, NEEDS TO BE CONTACTED FOR MORE DETAILS", "3");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, USER_ID_ASSIGNEDTO)
VALUES (3, "LOGIN FAILURE", "5");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "PRINTER ISSUE", "PRINTER WAS TURNED OFF, USER IS ABLE TO PRINT NOW", "3");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "LOGIN FAILURE", "ACCOUNT LOCKED DUE TOO MANY UNSUCCESSFUL LOGIN ATTEMPTS, USER TO BE CONTACTED", "1");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "PRINTER ISSUE", "ISSUE UNDER INVESTIGATION WITH USER", "3");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "LOGIN FAILURE", "CASE ASSIGNED TO THE RIGHT DEPARTMENT", "2");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, USER_ID_ASSIGNEDTO)
VALUES (2, "FILES DELETED", "4");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "FILES DELETED", "DATA TO BE RECOVERED", "4");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "FILES DELETED", "FILES RESTORED", "4");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "LOGIN FAILURE", "TICKET ASSIGNED TO RIGHT DEPARTMENT IN ORDER TO RESET THE PASSWORD", "4");

COMMIT;
