USE kodilla_tester;

SELECT I.SUMMARY, I.DESCRIPTION, IL.NAME AS ISSUE_CATEGORY
FROM ISSUES I
JOIN ISSUESLISTS IL
ON IL.ID = I.ISSUESLIST_ID;


SELECT I.SUMMARY, I.DESCRIPTION, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U
ON U.ID = I.USER_ID_ASSIGNEDTO;


SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ASSIGNED_ISSUES
FROM USERS U
JOIN ISSUES I
ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY U.ID
HAVING COUNT(*) > 0;
